---
title: "Beveridge-Nelson Filter Australia"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The package includes the latest Australian real/chain volume GDP and the Unemployment Rate through to December quarter 2024. 

```{r setup}
library(bnfilter)
tail(audata)
```

Load the GDP data from the package dataset

```{r fig.width = 7, fig.height = 5}
gdp <- ts(audata$GDPC1, start=c(1959,3), freq=4)
plot(gdp)
```

Take the logs of GDP

```{r}
y <- transform_series(gdp, take_log=TRUE, pcode="p1")
```

Example with no demeaning

```{r fig.width = 7, fig.height = 5}
plot(bnf(y=y, 
         demean="nd"))
```

Example with dynamic demean 

```{r fig.width = 7, fig.height = 5}
plot(bnf(y=y, 
         demean="dm"))
```

Example with dynamic adjusted confidence bands: 

```{r fig.width = 7, fig.height = 5}
plot(bnf(y=y, 
         demean="dm", 
         dynamic_bands = TRUE))
```

Example removing outliers for June and September quarters 2020 (COVID19):

```{r fig.width = 7, fig.height = 5}
plot(bnf(y=y, 
         demean="dm", 
         adjusted_bands = TRUE, 
         outliers = c(244,245)))
```
